[Variables]

//Font Variables
TextColor=0,0,0,255
TextColor2=255,255,255,255
Font1=Times New Yorker

//Picture Variables
//Size of program icons and the VT logo, or whatever is the center picture
MainImage=#SkinsPath#\Kara\Resources\Images\Main.png
Main2Image=#SkinsPath#\Kara\Resources\Images\Main_2.png
CenterImage=#SkinsPath#\Kara\Resources\Images\VTLogoB.png
CenterImageNotes=#SkinsPath#\Kara\Resources\Images\VTLogo.png
NotesBackground=#SkinsPath#\Kara\Resources\Images\NoteTest.png
IconSize=50
VTW=168
VTH=123

//Battery Variables
BatteryPath=#SkinsPath#\Kara\Resources\Images\Battery\KaraB.png

//Notes2 Test Variables
MinimizeBackground=#SkinsPath#\Kara\Resources\Images\Min.png
NotesFont=Lucida Console
NotesFontSize=10

//PictureBox Variables
PictureBox=#SkinsPath#\Kara\Resources\Images\PictureBox\Box.png
PictureBoxBGPath=#SkinsPath#\Kara\Resources\Images\PictureBox\Backgrounds

//Note Variables
//Width, Height, etc.
NotesW=236
NotesH=259.5
NotePath=#SkinsPath#\Kara\Notes\Notes.txt

//Hexagon
//Holds images for the hexagon
HImage=#SkinsPath#\Kara\Resources\Images\Hexagon.png

//App  + EE Variables
//Holds the name, image, and path for the apps and all the EE paths/links
VTLoc=#SkinsPath#\Kara\Resources\Images\Shh\NarutoandHinata.png
ReadLink=http://www.mangasee.com/manga/?series=Naruto&chapter=615&index=1
NoteLink=#SkinsPath#\Kara\Resources\Images\Shh\LastPanel.txt

App1Name=Chrome
App1Image=#SkinsPath#\Kara\Resources\Images\Apps\App1.png
App1Path=C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

App2Name=Control Panel 
App2Image=#SkinsPath#\Kara\Resources\Images\Apps\App2.png
App2Path=C:/Windows/System32/Control.exe

App3Name=My Documents
App3Image=#SkinsPath#\Kara\Resources\Images\Apps\App3.png
App3Path=C:\Users\Vaillancourt\Documents

App4Name=OneNote
App4Image=#SkinsPath#\Kara\Resources\Images\Apps\App4.png
App4Path=C:\Program Files\Microsoft Office\Office15\ONENOTE.exe

App5Name=Skype
App5Image=#SkinsPath#\Kara\Resources\Images\Apps\App5.png
App5Path=C:\Program Files (x86)\Skype\Phone\Skype.exe

App6Name=Photoshop
App6Image=#SkinsPath#\Kara\Resources\Images\Apps\App6.png
App6Path=C:\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe

App7Name=My Computer
App7Image=#SkinsPath#\Kara\Resources\Images\Apps\App7.png
App7Path=C:


App8Name=My VT
App8Image=#SkinsPath#\Kara\Resources\Images\Apps\App8.png
App8Path=https://my.vt.edu/render.userLayoutRootNode.uP?uP_root=root&uP_sparam=activeTab&activeTab=1

App9Name=Photos
App9Image=#SkinsPath#\Kara\Resources\Images\Apps\App9.png
App9Path=C:\Users\Vaillancourt\Pictures

App10Name=HokieSpa
App10Image=#SkinsPath#\Kara\Resources\Images\Apps\App10.png
App10Path=https://banweb.banner.vt.edu/ssb/prod/twbkwbis.P_GenMenu?name=bmenu.P_MainMnu

App11Name=Scholar
App11Image=#SkinsPath#\Kara\Resources\Images\Apps\App11.png
App11Path=https://scholar.vt.edu/portal

App12Name=Gmail
App12Image=#SkinsPath#\Kara\Resources\Images\Apps\App12.png
App12Path=http://mail.google.com/

App1Name-P2=Excel
App1Image-P2=#SkinsPath#\Kara\Resources\Images\Apps\App1-P2.png
App1Path-P2=C:\Program Files\Microsoft Office\Office15\Excel.exe

App2Name-P2=Linkedin
App2Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\download.png
App2Path-P2=http://www.linkedin.com/

App3Name-P2=Notepad
App3Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\natepad2.png
App3Path-P2=%windir%\system32\notepad.exe

App4Name-P2=Team Viewer 9
App4Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\tvi9.png
App4Path-P2=C:\Program Files (x86)\TeamViewer\Version9\TeamViewer.exe

App5Name-P2=Pinterest
App5Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\pin.png
App5Path-P2=http://www.pinterest.com/

App6-P2Name=Pandora
App6Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\pandora-logo.png
App6Path-P2=http://www.pandora.com/

App7Name-P2=Zune
App7Image-P2=#SkinsPath#\Kara\Resources\Images\Apps\App2-P2.png
App7Path-P2=C:\Program Files\Zune\Zune.exe

App8Name-P2=FireFox
App8Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\firefox-512.png
App8Path-P2=C:\Program Files (x86)\Mozilla Firefox\fireFox.exe

App9Name-P2=Unity
App9Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\unity.png
App9Path-P2=C:\Program Files (x86)\Unity\Editor\Unity.exe

App10Name-P2=InDesign
App10Image-P2=C:\Users\Vaillancourt\Documents\Rainmeter\Skins\Kara\Resources\Images\Apps\indesign.png
App10Path-P2=C:\Adobe\Adobe InDesign CS6\InDesign.exe

App11-P2Name=Arduino
App11Image-P2=#SkinsPath#\Kara\Resources\Images\Apps\arduino_logo.png
App11Path-P2=C:\Program Files (x86)\Arduino\arduino.exe

App12Name-P2=
App12Image-P2=
App12Path-P2=


AppK2Name=Google Drive
AppK2Image=#SkinsPath#\Kara\Resources\Images\Apps\AppK2.png
AppK2Path=C:\Users\Vaillancourt\Google Drive

AppK3Name=Facebook
AppK3Image=#SkinsPath#\Kara\Resources\Images\Apps\AppK3.png
AppK3Path=https://www.facebook.com/

AppK11Name=Microsoft Word
AppK11Image=#SkinsPath#\Kara\Resources\Images\Apps\AppK11.png
AppK11Path=C:\Program Files\Microsoft Office\Office15\WINWORD.exe


AppK10Name=Eclipse
AppK10Image=#SkinsPath#\Kara\Resources\Images\Apps\eclipse.png
AppK10Path=C:\EclipseAndroid\adt-bundle-windows-x86_64-20140321\eclipse\eclipse.exe

AppK12Name=MatLab
AppK12Image=#SkinsPath#\Kara\Resources\Images\Apps\BubbleMatlab.png
Appk12Path=C:\Program Files\MATLAB\R2013b\bin\matlab.exe

AppK9Name=Bluetooth
AppK9Image=#SkinsPath#\Kara\Resources\Images\Apps\bluetooth_circle.png
AppK9Path=Shell:::{28803F59-3A75-4058-995F-4EE5503B023C}

